name: DevSecOps Pipeline

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

permissions:
  contents: read
  security-events: write

jobs:
  build-and-test:
    name: Build, Test & SCA Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install dependencies and build app
        run: npm install

      - name: Smoke Test
        run: |
          npm start &
          sleep 30
          curl -f http://localhost:3000

      - name: Run SCA scan with npm audit
        run: npm audit --audit-level=high || true

  sast-scan:
    name: Static Code Analysis (SAST)
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      # NOWY, POPRAWNY SPOSÓB URUCHOMIENIA SEMGREP
      - name: Run Semgrep SAST scan
        # Używamy oficjalnego obrazu Docker semgrep/ci
        uses: docker://semgrep/ci
        env:
          # Przekazujemy token, który zapisaliśmy w sekretach
          SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}