name: DevSecOps Pipeline

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

permissions:
  contents: read
  security-events: write

jobs:
  # Zadanie 1: Pozostaje bez zmian
  build-and-test:
    name: Build, Test & SCA Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4
      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Install dependencies and build app
        run: npm install
      - name: Smoke Test
        run: |
          npm start &
          sleep 30
          curl -f http://localhost:3000
      - name: Run SCA scan with npm audit
        run: npm audit --audit-level=high || true

  # Zadanie 2: Skanowanie SAST - teraz w 100% zgodne z dokumentacją
  sast-scan:
    name: Static Code Analysis (SAST)
    needs: build-and-test
    runs-on: ubuntu-latest
    
    # KROK 1: Uruchamiamy całe zadanie wewnątrz kontenera Semgrep
    container:
      image: semgrep/semgrep:latest # Używamy oficjalnego obrazu

    steps:
      # Krok 2: Pobieramy kod DO kontenera
      - name: Checkout repository code
        uses: actions/checkout@v4

      # Krok 3: Uruchamiamy komendę semgrep ci wewnątrz kontenera
      - name: Run Semgrep SAST scan
        run: semgrep ci
        env:
          # Przekazujemy nasz token API do kontenera
          SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}

  secrets-scan:
    name: Secrets Scan
    needs: build-and-test # Uruchom po zadaniu 1, może działać równolegle z SAST
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4
        # Musimy pobrać pełną historię, aby skaner mógł porównać zmiany
        with:
          fetch-depth: 0 

      - name: Run TruffleHog secrets scan
        # Używamy oficjalnej akcji od TruffleHog
        uses: trufflesecurity/trufflehog@main
        with:
          # Skanuj tylko zmiany od ostatniego pusha - bardzo szybkie
          base: ${{ github.event.before }}
          head: ${{ github.sha }}
          # Dodatkowe flagi dla lepszych wyników
          extra_args: --only-verified
        continue-on-error: true
        
   dast-scan:
    name: Dynamic Analysis (DAST)
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      # Krok 1: Uruchom kontener z aplikacją Juice Shop w tle
      # Dajemy mu nazwę 'juice_shop_for_scan', żeby łatwo się do niego odnieść
      - name: Start Juice Shop container
        run: docker run -d --name juice_shop_for_scan -p 3000:3000 bkimminich/juice-shop

      # Krok 2: Czekamy chwilę, żeby aplikacja wstała
      - name: Wait for application to start
        run: sleep 30

      # Krok 3: Uruchamiamy skanowanie ZAP, wskazując na działający kontener
      - name: OWASP ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.11.0
        with:
          # Cel skanowania - ZAP będzie miał dostęp do tego adresu,
          # bo oba kontenery działają w tej samej sieci runnera
          target: 'http://localhost:3000/'
          artifact_name: zap_scan_report